name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine Theme
        id: theme
        run: |
          # Determine if the GitHub theme is dark or light
          THEME=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${GITHUB_REPOSITORY}/themes | grep -o '"theme":.*[^,}]' | cut -d'"' -f4)
          if [ "$THEME" == "dark" ]; then
            echo "dark"
          else
            echo "light"
          fi
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Update README
        run: |
          # Replace the image URL in README.md based on the theme
          if [ "${{ steps.theme.outputs.theme }}" == "dark" ]; then
            sed -i 's/github-contribution-grid-snake.svg/github-contribution-grid-snake-dark.svg/g' README.md
          else
            sed -i 's/github-contribution-grid-snake-dark.svg/github-contribution-grid-snake.svg/g' README.md
          fi

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update contribution grid based on theme"
          git push
